'''
Neuron simulator export for:

Components:
    null (Type: notes)
    ar__m00 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    cal (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    cat_a (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    k2 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    ka (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kahp_slower (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kc (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr_fs (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    km (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    naf2__a0__b0__c0__d0__fastNa_shift0 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    pas (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    nRTc (Type: cell)
    input_0_2nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=2.0000000000000003E-10 (SI current))
    input_0_25nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=2.5E-10 (SI current))
    input_0_3nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=3.0E-10 (SI current))
    input_0_35nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=3.5E-10 (SI current))
    input_0_39999999999999997nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=4.0E-10 (SI current))
    input_0_44999999999999996nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=4.5E-10 (SI current))
    input_0_49999999999999994nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=4.999999999999999E-10 (SI current))
    input_0_5499999999999999nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=5.5E-10 (SI current))
    input_0_6nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=6.0E-10 (SI current))
    input_0_65nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=6.5E-10 (SI current))
    input_0_7000000000000001nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=7.000000000000001E-10 (SI current))
    input_0_7500000000000001nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=7.500000000000002E-10 (SI current))
    input_0_8000000000000002nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=8.000000000000002E-10 (SI current))
    input_0_8500000000000002nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=8.500000000000003E-10 (SI current))
    input_0_9000000000000002nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=9.000000000000003E-10 (SI current))
    input_0_9500000000000003nA (Type: pulseGenerator:  delay=0.0 (SI time) duration=0.03 (SI time) amplitude=9.500000000000004E-10 (SI current))
    network_of_nRTc (Type: networkWithTemperature:  temperature=305.15 (SI temperature))
    iv_nRTc (Type: Simulation:  length=0.03 (SI time) step=1.0E-5 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

'''

import neuron

import time
import datetime
import sys

import hashlib
h = neuron.h
h.load_file("stdlib.hoc")

h.load_file("stdgui.hoc")

h("objref p")
h("p = new PythonObject()")

class NeuronSimulation():

    def __init__(self, tstop, dt=None, seed=12345, abs_tol=None, rel_tol=None):

        print("\n    Starting simulation in NEURON of %sms generated from NeuroML2 model...\n"%tstop)

        self.setup_start = time.time()
        self.seed = seed
        self.abs_tol = abs_tol
        self.rel_tol = rel_tol
        self.randoms = []
        self.next_global_id = 0  # Used in Random123 classes for elements using random(), etc. 

        self.next_spiking_input_id = 0  # Used in Random123 classes for elements using random(), etc. 

        '''
        Adding simulation Component(id=iv_nRTc type=Simulation) of network/component: network_of_nRTc (Type: networkWithTemperature:  temperature=305.15 (SI temperature))
        
        '''

        # Temperature used for network: 305.15 K
        h.celsius = 305.15 - 273.15

        # ######################   Population: population_of_nRTc
        print("Population population_of_nRTc contains 16 instance(s) of component: nRTc of type: cell")

        h.load_file("nRTc.hoc")
        a_population_of_nRTc = []
        h("{ n_population_of_nRTc = 16 }")
        h("objectvar a_population_of_nRTc[n_population_of_nRTc]")
        for i in range(int(h.n_population_of_nRTc)):
            h("a_population_of_nRTc[%i] = new nRTc()"%i)
            h("access a_population_of_nRTc[%i].soma_0"%i)

            self.next_global_id+=1


        h("proc initialiseV_population_of_nRTc() { for i = 0, n_population_of_nRTc-1 { a_population_of_nRTc[i].set_initial_v() } }")
        h("objref fih_population_of_nRTc")
        h('{fih_population_of_nRTc = new FInitializeHandler(0, "initialiseV_population_of_nRTc()")}')

        h("proc initialiseIons_population_of_nRTc() { for i = 0, n_population_of_nRTc-1 { a_population_of_nRTc[i].set_initial_ion_properties() } }")
        h("objref fih_ion_population_of_nRTc")
        h('{fih_ion_population_of_nRTc = new FInitializeHandler(1, "initialiseIons_population_of_nRTc()")}')

        print("Processing 16 input lists")

        # ######################   Input List: input_0_2nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_2nA_0")
        h("a_population_of_nRTc[0].soma_0 { input_0_2nA_0 = new input_0_2nA(0.25) } ")

        # ######################   Input List: input_0_25nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_25nA_0")
        h("a_population_of_nRTc[1].soma_0 { input_0_25nA_0 = new input_0_25nA(0.25) } ")

        # ######################   Input List: input_0_3nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_3nA_0")
        h("a_population_of_nRTc[2].soma_0 { input_0_3nA_0 = new input_0_3nA(0.25) } ")

        # ######################   Input List: input_0_35nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_35nA_0")
        h("a_population_of_nRTc[3].soma_0 { input_0_35nA_0 = new input_0_35nA(0.25) } ")

        # ######################   Input List: input_0_39999999999999997nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_39999999999999997nA_0")
        h("a_population_of_nRTc[4].soma_0 { input_0_39999999999999997nA_0 = new input_0_39999999999999997nA(0.25) } ")

        # ######################   Input List: input_0_44999999999999996nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_44999999999999996nA_0")
        h("a_population_of_nRTc[5].soma_0 { input_0_44999999999999996nA_0 = new input_0_44999999999999996nA(0.25) } ")

        # ######################   Input List: input_0_49999999999999994nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_49999999999999994nA_0")
        h("a_population_of_nRTc[6].soma_0 { input_0_49999999999999994nA_0 = new input_0_49999999999999994nA(0.25) } ")

        # ######################   Input List: input_0_5499999999999999nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_5499999999999999nA_0")
        h("a_population_of_nRTc[7].soma_0 { input_0_5499999999999999nA_0 = new input_0_5499999999999999nA(0.25) } ")

        # ######################   Input List: input_0_6nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_6nA_0")
        h("a_population_of_nRTc[8].soma_0 { input_0_6nA_0 = new input_0_6nA(0.25) } ")

        # ######################   Input List: input_0_65nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_65nA_0")
        h("a_population_of_nRTc[9].soma_0 { input_0_65nA_0 = new input_0_65nA(0.25) } ")

        # ######################   Input List: input_0_7000000000000001nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_7000000000000001nA_0")
        h("a_population_of_nRTc[10].soma_0 { input_0_7000000000000001nA_0 = new input_0_7000000000000001nA(0.25) } ")

        # ######################   Input List: input_0_7500000000000001nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_7500000000000001nA_0")
        h("a_population_of_nRTc[11].soma_0 { input_0_7500000000000001nA_0 = new input_0_7500000000000001nA(0.25) } ")

        # ######################   Input List: input_0_8000000000000002nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_8000000000000002nA_0")
        h("a_population_of_nRTc[12].soma_0 { input_0_8000000000000002nA_0 = new input_0_8000000000000002nA(0.25) } ")

        # ######################   Input List: input_0_8500000000000002nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_8500000000000002nA_0")
        h("a_population_of_nRTc[13].soma_0 { input_0_8500000000000002nA_0 = new input_0_8500000000000002nA(0.25) } ")

        # ######################   Input List: input_0_9000000000000002nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_9000000000000002nA_0")
        h("a_population_of_nRTc[14].soma_0 { input_0_9000000000000002nA_0 = new input_0_9000000000000002nA(0.25) } ")

        # ######################   Input List: input_0_9500000000000003nA
        # Adding single input: Component(id=0 type=input)
        h("objref input_0_9500000000000003nA_0")
        h("a_population_of_nRTc[15].soma_0 { input_0_9500000000000003nA_0 = new input_0_9500000000000003nA(0.25) } ")

        print("Finished processing 16 input lists")

        trec = h.Vector()
        trec.record(h._ref_t)

        h.tstop = tstop

        if self.abs_tol is not None and self.rel_tol is not None:
            cvode = h.CVode()
            cvode.active(1)
            cvode.atol(self.abs_tol)
            cvode.rtol(self.rel_tol)
        else:
            h.dt = dt
            h.steps_per_ms = 1/h.dt



        # ######################   File to save: iv_nRTc.v.dat (Volts_file)
        # Column: population_of_nRTc[0]/v
        h(' objectvar v_v_cell0_Volts_file ')
        h(' { v_v_cell0_Volts_file = new Vector() } ')
        h(' { v_v_cell0_Volts_file.record(&a_population_of_nRTc[0].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell0_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[1]/v
        h(' objectvar v_v_cell1_Volts_file ')
        h(' { v_v_cell1_Volts_file = new Vector() } ')
        h(' { v_v_cell1_Volts_file.record(&a_population_of_nRTc[1].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell1_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[2]/v
        h(' objectvar v_v_cell2_Volts_file ')
        h(' { v_v_cell2_Volts_file = new Vector() } ')
        h(' { v_v_cell2_Volts_file.record(&a_population_of_nRTc[2].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell2_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[3]/v
        h(' objectvar v_v_cell3_Volts_file ')
        h(' { v_v_cell3_Volts_file = new Vector() } ')
        h(' { v_v_cell3_Volts_file.record(&a_population_of_nRTc[3].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell3_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[4]/v
        h(' objectvar v_v_cell4_Volts_file ')
        h(' { v_v_cell4_Volts_file = new Vector() } ')
        h(' { v_v_cell4_Volts_file.record(&a_population_of_nRTc[4].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell4_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[5]/v
        h(' objectvar v_v_cell5_Volts_file ')
        h(' { v_v_cell5_Volts_file = new Vector() } ')
        h(' { v_v_cell5_Volts_file.record(&a_population_of_nRTc[5].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell5_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[6]/v
        h(' objectvar v_v_cell6_Volts_file ')
        h(' { v_v_cell6_Volts_file = new Vector() } ')
        h(' { v_v_cell6_Volts_file.record(&a_population_of_nRTc[6].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell6_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[7]/v
        h(' objectvar v_v_cell7_Volts_file ')
        h(' { v_v_cell7_Volts_file = new Vector() } ')
        h(' { v_v_cell7_Volts_file.record(&a_population_of_nRTc[7].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell7_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[8]/v
        h(' objectvar v_v_cell8_Volts_file ')
        h(' { v_v_cell8_Volts_file = new Vector() } ')
        h(' { v_v_cell8_Volts_file.record(&a_population_of_nRTc[8].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell8_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[9]/v
        h(' objectvar v_v_cell9_Volts_file ')
        h(' { v_v_cell9_Volts_file = new Vector() } ')
        h(' { v_v_cell9_Volts_file.record(&a_population_of_nRTc[9].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell9_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[10]/v
        h(' objectvar v_v_cell10_Volts_file ')
        h(' { v_v_cell10_Volts_file = new Vector() } ')
        h(' { v_v_cell10_Volts_file.record(&a_population_of_nRTc[10].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell10_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[11]/v
        h(' objectvar v_v_cell11_Volts_file ')
        h(' { v_v_cell11_Volts_file = new Vector() } ')
        h(' { v_v_cell11_Volts_file.record(&a_population_of_nRTc[11].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell11_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[12]/v
        h(' objectvar v_v_cell12_Volts_file ')
        h(' { v_v_cell12_Volts_file = new Vector() } ')
        h(' { v_v_cell12_Volts_file.record(&a_population_of_nRTc[12].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell12_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[13]/v
        h(' objectvar v_v_cell13_Volts_file ')
        h(' { v_v_cell13_Volts_file = new Vector() } ')
        h(' { v_v_cell13_Volts_file.record(&a_population_of_nRTc[13].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell13_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[14]/v
        h(' objectvar v_v_cell14_Volts_file ')
        h(' { v_v_cell14_Volts_file = new Vector() } ')
        h(' { v_v_cell14_Volts_file.record(&a_population_of_nRTc[14].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell14_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: population_of_nRTc[15]/v
        h(' objectvar v_v_cell15_Volts_file ')
        h(' { v_v_cell15_Volts_file = new Vector() } ')
        h(' { v_v_cell15_Volts_file.record(&a_population_of_nRTc[15].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_v_cell15_Volts_file.resize((h.tstop * h.steps_per_ms) + 1)

        # ######################   File to save: time.dat (time)
        # Column: time
        h(' objectvar v_time ')
        h(' { v_time = new Vector() } ')
        h(' { v_time.record(&t) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

        self.initialized = False

        self.sim_end = -1 # will be overwritten

        setup_end = time.time()
        self.setup_time = setup_end - self.setup_start
        print("Setting up the network to simulate took %f seconds"%(self.setup_time))

    def run(self):

        self.initialized = True
        sim_start = time.time()
        if self.abs_tol is not None and self.rel_tol is not None:
            print("Running a simulation of %sms (cvode abs_tol = %sms, rel_tol = %sms; seed=%s)" % (h.tstop, self.abs_tol, self.rel_tol, self.seed))
        else:
            print("Running a simulation of %sms (dt = %sms; seed=%s)" % (h.tstop, h.dt, self.seed))

        try:
            h.run()
        except Exception as e:
            print("Exception running NEURON: %s" % (e))
            quit()


        self.sim_end = time.time()
        self.sim_time = self.sim_end - sim_start
        print("Finished NEURON simulation in %f seconds (%f mins)..."%(self.sim_time, self.sim_time/60.0))

        try:
            self.save_results()
        except Exception as e:
            print("Exception saving results of NEURON simulation: %s" % (e))
            quit()


    def advance(self):

        if not self.initialized:
            h.finitialize()
            self.initialized = True

        h.fadvance()


    ###############################################################################
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj.encode('utf-8')).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int


    ###############################################################################
    # Initialize the stim randomizer
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _init_stim_randomizer(self,rand, stimType, gid, seed): 
        #print("INIT STIM  %s; %s; %s; %s"%(rand, stimType, gid, seed))
        rand.Random123(self._id32(stimType), gid, seed)


    def save_results(self):

        print("Saving results at t=%s..."%h.t)

        if self.sim_end < 0: self.sim_end = time.time()


        # ######################   File to save: time.dat (time). Note, saving in SI units
        py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

        f_time_f2 = open('time.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...
        f_time_f2.close()
        print("Saved data to: time.dat")

        # ######################   File to save: iv_nRTc.v.dat (Volts_file). Note, saving in SI units
        py_v_v_cell0_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell0_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell1_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell1_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell2_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell2_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell3_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell3_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell4_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell4_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell5_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell5_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell6_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell6_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell7_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell7_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell8_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell8_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell9_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell9_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell10_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell10_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell11_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell11_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell12_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell12_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell13_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell13_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell14_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell14_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_v_cell15_Volts_file = [ float(x  / 1000.0) for x in h.v_v_cell15_Volts_file.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

        f_Volts_file_f2 = open('iv_nRTc.v.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_Volts_file_f2.write('%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t\n' % (py_v_time[i], py_v_v_cell0_Volts_file[i], py_v_v_cell1_Volts_file[i], py_v_v_cell2_Volts_file[i], py_v_v_cell3_Volts_file[i], py_v_v_cell4_Volts_file[i], py_v_v_cell5_Volts_file[i], py_v_v_cell6_Volts_file[i], py_v_v_cell7_Volts_file[i], py_v_v_cell8_Volts_file[i], py_v_v_cell9_Volts_file[i], py_v_v_cell10_Volts_file[i], py_v_v_cell11_Volts_file[i], py_v_v_cell12_Volts_file[i], py_v_v_cell13_Volts_file[i], py_v_v_cell14_Volts_file[i], py_v_v_cell15_Volts_file[i], ))
        f_Volts_file_f2.close()
        print("Saved data to: iv_nRTc.v.dat")

        save_end = time.time()
        save_time = save_end - self.sim_end
        print("Finished saving results in %f seconds"%(save_time))

        print("Done")

        quit()


if __name__ == '__main__':

    ns = NeuronSimulation(tstop=30.0, dt=0.01, seed=12345, abs_tol=None, rel_tol=None)

    ns.run()

