'''
Neuron simulator export for:

Components:
    null (Type: notes)
    null (Type: notes)
    ar__m00 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    cal (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    cat_a (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    k2 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    ka (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kahp_slower (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kc (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    kdr_fs (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    km (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    naf2__a0__b0__c0__d0__fastNa_shift0 (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    pas (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    nRTc (Type: cell)
    pg_nRTil (Type: pulseGenerator:  delay=0.1 (SI time) duration=0.1 (SI time) amplitude=8.000000000000001E-11 (SI current))
    sg_nRTil (Type: sineGenerator:  phase=2.0 (dimensionless) delay=0.05 (SI time) duration=0.2 (SI time) amplitude=1.4E-9 (SI current) period=0.05 (SI time))
    rg_nRTil (Type: rampGenerator:  delay=0.05 (SI time) duration=0.2 (SI time) startAmplitude=5.0E-10 (SI current) finishAmplitude=4.0E-9 (SI current) baselineAmplitude=0.0 (SI current))
    vClamp_nRTil (Type: voltageClampTriple:  active=1.0 (dimensionless) delay=0.05 (SI time) duration=0.2 (SI time) conditioningVoltage=-0.07 (SI voltage) testingVoltage=-0.05 (SI voltage) returnVoltage=-0.07 (SI voltage) simpleSeriesResistance=1000000.0 (SI resistance))
    nRTc_net (Type: network)
    nRTc_sim (Type: Simulation:  length=0.2 (SI time) step=1.0E-5 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

'''

import neuron

import time
import datetime
import sys

import hashlib
h = neuron.h
h.load_file("stdlib.hoc")

h.load_file("stdgui.hoc")

h("objref p")
h("p = new PythonObject()")

class NeuronSimulation():

    def __init__(self, tstop, dt=None, seed=123, abs_tol=None, rel_tol=None):

        print("\n    Starting simulation in NEURON of %sms generated from NeuroML2 model...\n"%tstop)

        self.setup_start = time.time()
        self.seed = seed
        self.abs_tol = abs_tol
        self.rel_tol = rel_tol
        self.randoms = []
        self.next_global_id = 0  # Used in Random123 classes for elements using random(), etc. 

        self.next_spiking_input_id = 0  # Used in Random123 classes for elements using random(), etc. 

        '''
        Adding simulation Component(id=nRTc_sim type=Simulation) of network/component: nRTc_net (Type: network)
        
        '''
        # ######################   Population: pop0
        print("Population pop0 contains 1 instance(s) of component: nRTc of type: cell")

        h.load_file("nRTc.hoc")
        a_pop0 = []
        h("{ n_pop0 = 1 }")
        h("objectvar a_pop0[n_pop0]")
        for i in range(int(h.n_pop0)):
            h("a_pop0[%i] = new nRTc()"%i)
            h("access a_pop0[%i].soma_0"%i)

            self.next_global_id+=1

        h("{ a_pop0[0].position(0.0, 0.0, 0.0) }")

        h("proc initialiseV_pop0() { for i = 0, n_pop0-1 { a_pop0[i].set_initial_v() } }")
        h("objref fih_pop0")
        h('{fih_pop0 = new FInitializeHandler(0, "initialiseV_pop0()")}')

        h("proc initialiseIons_pop0() { for i = 0, n_pop0-1 { a_pop0[i].set_initial_ion_properties() } }")
        h("objref fih_ion_pop0")
        h('{fih_ion_pop0 = new FInitializeHandler(1, "initialiseIons_pop0()")}')

        # Adding single input: Component(id=null type=explicitInput)
        h("objref explicitInput_sg_nRTila_pop0_0__soma_0")
        h("a_pop0[0].soma_0 { explicitInput_sg_nRTila_pop0_0__soma_0 = new sg_nRTil(0.25) } ")

        trec = h.Vector()
        trec.record(h._ref_t)

        h.tstop = tstop

        if self.abs_tol is not None and self.rel_tol is not None:
            cvode = h.CVode()
            cvode.active(1)
            cvode.atol(self.abs_tol)
            cvode.rtol(self.rel_tol)
        else:
            h.dt = dt
            h.steps_per_ms = 1/h.dt



        # ######################   File to save: time.dat (time)
        # Column: time
        h(' objectvar v_time ')
        h(' { v_time = new Vector() } ')
        h(' { v_time.record(&t) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

        # ######################   File to save: nRTc_sim.dat (output0)
        # Column: pop0[0]/v
        h(' objectvar v_pop0_0_v_output0 ')
        h(' { v_pop0_0_v_output0 = new Vector() } ')
        h(' { v_pop0_0_v_output0.record(&a_pop0[0].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/0/v
        h(' objectvar v_pop0_0_v_Seg0_soma_0_output0 ')
        h(' { v_pop0_0_v_Seg0_soma_0_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_soma_0_output0.record(&a_pop0[0].soma_0.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_soma_0_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/1/v
        h(' objectvar v_pop0_0_v_Seg1_soma_0_output0 ')
        h(' { v_pop0_0_v_Seg1_soma_0_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_soma_0_output0.record(&a_pop0[0].soma_0.v(0.75)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_soma_0_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/2/v
        h(' objectvar v_pop0_0_v_Seg0_axon_0_output0 ')
        h(' { v_pop0_0_v_Seg0_axon_0_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_axon_0_output0.record(&a_pop0[0].axon_0.v(0.1875)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_axon_0_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/3/v
        h(' objectvar v_pop0_0_v_Seg1_axon_0_output0 ')
        h(' { v_pop0_0_v_Seg1_axon_0_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_axon_0_output0.record(&a_pop0[0].axon_0.v(0.6875)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_axon_0_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/4/v
        h(' objectvar v_pop0_0_v_Seg0_axon_1_output0 ')
        h(' { v_pop0_0_v_Seg0_axon_1_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_axon_1_output0.record(&a_pop0[0].axon_1.v(0.25)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_axon_1_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/5/v
        h(' objectvar v_pop0_0_v_Seg1_axon_1_output0 ')
        h(' { v_pop0_0_v_Seg1_axon_1_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_axon_1_output0.record(&a_pop0[0].axon_1.v(0.75)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_axon_1_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/6/v
        h(' objectvar v_pop0_0_v_Seg0_axon_2_output0 ')
        h(' { v_pop0_0_v_Seg0_axon_2_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_axon_2_output0.record(&a_pop0[0].axon_2.v(0.24999776)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_axon_2_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/7/v
        h(' objectvar v_pop0_0_v_Seg1_axon_2_output0 ')
        h(' { v_pop0_0_v_Seg1_axon_2_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_axon_2_output0.record(&a_pop0[0].axon_2.v(0.7499978)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_axon_2_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/8/v
        h(' objectvar v_pop0_0_v_Seg0_axon_3_output0 ')
        h(' { v_pop0_0_v_Seg0_axon_3_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_axon_3_output0.record(&a_pop0[0].axon_3.v(0.29900572)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_axon_3_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/9/v
        h(' objectvar v_pop0_0_v_Seg1_axon_3_output0 ')
        h(' { v_pop0_0_v_Seg1_axon_3_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_axon_3_output0.record(&a_pop0[0].axon_3.v(0.79900575)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_axon_3_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/10/v
        h(' objectvar v_pop0_0_v_Seg0_axon_4_output0 ')
        h(' { v_pop0_0_v_Seg0_axon_4_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_axon_4_output0.record(&a_pop0[0].axon_4.v(0.24999774)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_axon_4_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/11/v
        h(' objectvar v_pop0_0_v_Seg1_axon_4_output0 ')
        h(' { v_pop0_0_v_Seg1_axon_4_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_axon_4_output0.record(&a_pop0[0].axon_4.v(0.74999774)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_axon_4_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/12/v
        h(' objectvar v_pop0_0_v_Seg0_axon_5_output0 ')
        h(' { v_pop0_0_v_Seg0_axon_5_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_axon_5_output0.record(&a_pop0[0].axon_5.v(0.24999519)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_axon_5_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/13/v
        h(' objectvar v_pop0_0_v_Seg1_axon_5_output0 ')
        h(' { v_pop0_0_v_Seg1_axon_5_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_axon_5_output0.record(&a_pop0[0].axon_5.v(0.7499952)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_axon_5_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/14/v
        h(' objectvar v_pop0_0_v_Seg0_dend_0_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_0_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_0_output0.record(&a_pop0[0].primary_dend_0.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_0_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/15/v
        h(' objectvar v_pop0_0_v_Seg1_dend_0_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_0_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_0_output0.record(&a_pop0[0].primary_dend_0.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_0_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/16/v
        h(' objectvar v_pop0_0_v_Seg0_dend_1_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_1_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_1_output0.record(&a_pop0[0].primary_dend_1.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_1_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/17/v
        h(' objectvar v_pop0_0_v_Seg1_dend_1_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_1_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_1_output0.record(&a_pop0[0].primary_dend_1.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_1_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/18/v
        h(' objectvar v_pop0_0_v_Seg0_dend_2_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_2_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_2_output0.record(&a_pop0[0].primary_dend_2.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_2_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/19/v
        h(' objectvar v_pop0_0_v_Seg1_dend_2_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_2_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_2_output0.record(&a_pop0[0].primary_dend_2.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_2_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/20/v
        h(' objectvar v_pop0_0_v_Seg0_dend_3_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_3_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_3_output0.record(&a_pop0[0].primary_dend_3.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_3_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/21/v
        h(' objectvar v_pop0_0_v_Seg1_dend_3_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_3_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_3_output0.record(&a_pop0[0].primary_dend_3.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_3_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/22/v
        h(' objectvar v_pop0_0_v_Seg0_dend_4_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_4_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_4_output0.record(&a_pop0[0].primary_dend_4.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_4_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/23/v
        h(' objectvar v_pop0_0_v_Seg1_dend_4_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_4_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_4_output0.record(&a_pop0[0].primary_dend_4.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_4_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/24/v
        h(' objectvar v_pop0_0_v_Seg0_dend_5_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_5_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_5_output0.record(&a_pop0[0].primary_dend_5.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_5_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/25/v
        h(' objectvar v_pop0_0_v_Seg1_dend_5_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_5_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_5_output0.record(&a_pop0[0].primary_dend_5.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_5_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/26/v
        h(' objectvar v_pop0_0_v_Seg0_dend_6_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_6_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_6_output0.record(&a_pop0[0].primary_dend_6.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_6_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/27/v
        h(' objectvar v_pop0_0_v_Seg1_dend_6_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_6_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_6_output0.record(&a_pop0[0].primary_dend_6.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_6_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/28/v
        h(' objectvar v_pop0_0_v_Seg0_dend_7_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_7_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_7_output0.record(&a_pop0[0].primary_dend_7.v(0.13439798)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_7_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/29/v
        h(' objectvar v_pop0_0_v_Seg1_dend_7_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_7_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_7_output0.record(&a_pop0[0].primary_dend_7.v(0.634398)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_7_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/30/v
        h(' objectvar v_pop0_0_v_Seg0_dend_8_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_8_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_8_output0.record(&a_pop0[0].secondary_dend_0.v(0.13123083)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_8_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/31/v
        h(' objectvar v_pop0_0_v_Seg1_dend_8_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_8_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_8_output0.record(&a_pop0[0].secondary_dend_0.v(0.63123083)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_8_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/32/v
        h(' objectvar v_pop0_0_v_Seg1_dend_9_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_9_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_9_output0.record(&a_pop0[0].secondary_dend_1.v(0.13102025)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_9_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/33/v
        h(' objectvar v_pop0_0_v_Seg0_dend_9_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_9_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_9_output0.record(&a_pop0[0].secondary_dend_1.v(0.63102025)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_9_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/34/v
        h(' objectvar v_pop0_0_v_Seg1_dend_10_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_10_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_10_output0.record(&a_pop0[0].secondary_dend_2.v(0.13039729)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_10_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/35/v
        h(' objectvar v_pop0_0_v_Seg0_dend_10_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_10_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_10_output0.record(&a_pop0[0].secondary_dend_2.v(0.6303973)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_10_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/36/v
        h(' objectvar v_pop0_0_v_Seg1_dend_11_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_11_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_11_output0.record(&a_pop0[0].secondary_dend_3.v(0.12938742)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_11_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/37/v
        h(' objectvar v_pop0_0_v_Seg0_dend_11_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_11_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_11_output0.record(&a_pop0[0].secondary_dend_3.v(0.62938744)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_11_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/38/v
        h(' objectvar v_pop0_0_v_Seg1_dend_12_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_12_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_12_output0.record(&a_pop0[0].secondary_dend_4.v(0.12803006)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_12_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/39/v
        h(' objectvar v_pop0_0_v_Seg0_dend_12_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_12_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_12_output0.record(&a_pop0[0].secondary_dend_4.v(0.62803006)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_12_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/40/v
        h(' objectvar v_pop0_0_v_Seg1_dend_13_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_13_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_13_output0.record(&a_pop0[0].secondary_dend_5.v(0.12637477)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_13_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/41/v
        h(' objectvar v_pop0_0_v_Seg0_dend_13_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_13_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_13_output0.record(&a_pop0[0].secondary_dend_5.v(0.6263748)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_13_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/42/v
        h(' objectvar v_pop0_0_v_Seg1_dend_14_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_14_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_14_output0.record(&a_pop0[0].secondary_dend_6.v(0.12447693)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_14_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/43/v
        h(' objectvar v_pop0_0_v_Seg0_dend_14_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_14_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_14_output0.record(&a_pop0[0].secondary_dend_6.v(0.6244769)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_14_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/44/v
        h(' objectvar v_pop0_0_v_Seg1_dend_15_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_15_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_15_output0.record(&a_pop0[0].secondary_dend_7.v(0.12239365)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_15_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/45/v
        h(' objectvar v_pop0_0_v_Seg0_dend_15_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_15_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_15_output0.record(&a_pop0[0].secondary_dend_7.v(0.62239367)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_15_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/46/v
        h(' objectvar v_pop0_0_v_Seg1_dend_16_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_16_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_16_output0.record(&a_pop0[0].secondary_dend_8.v(0.12018029)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_16_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/47/v
        h(' objectvar v_pop0_0_v_Seg0_dend_16_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_16_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_16_output0.record(&a_pop0[0].secondary_dend_8.v(0.6201803)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_16_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/48/v
        h(' objectvar v_pop0_0_v_Seg1_dend_17_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_17_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_17_output0.record(&a_pop0[0].secondary_dend_9.v(0.1178879)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_17_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/49/v
        h(' objectvar v_pop0_0_v_Seg1_dend_17_output0_ ')
        h(' { v_pop0_0_v_Seg1_dend_17_output0_ = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_17_output0_.record(&a_pop0[0].secondary_dend_9.v(0.6178879)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_17_output0_.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/50/v
        h(' objectvar v_pop0_0_v_Seg0_dend_18_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_18_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_18_output0.record(&a_pop0[0].secondary_dend_10.v(0.11556172)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_18_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/51/v
        h(' objectvar v_pop0_0_v_Seg1_dend_18_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_18_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_18_output0.record(&a_pop0[0].secondary_dend_10.v(0.6155617)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_18_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/52/v
        h(' objectvar v_pop0_0_v_Seg0_dend_19_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_19_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_19_output0.record(&a_pop0[0].secondary_dend_11.v(0.113240406)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_19_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/53/v
        h(' objectvar v_pop0_0_v_Seg1_dend_19_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_19_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_19_output0.record(&a_pop0[0].secondary_dend_11.v(0.6132404)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_19_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/54/v
        h(' objectvar v_pop0_0_v_Seg0_dend_20_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_20_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_20_output0.record(&a_pop0[0].secondary_dend_12.v(0.11095597)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_20_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/55/v
        h(' objectvar v_pop0_0_v_Seg1_dend_20_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_20_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_20_output0.record(&a_pop0[0].secondary_dend_12.v(0.61095595)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_20_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/56/v
        h(' objectvar v_pop0_0_v_Seg0_dend_21_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_21_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_21_output0.record(&a_pop0[0].secondary_dend_13.v(0.10873412)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_21_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/57/v
        h(' objectvar v_pop0_0_v_Seg1_dend_21_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_21_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_21_output0.record(&a_pop0[0].secondary_dend_13.v(0.60873413)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_21_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/58/v
        h(' objectvar v_pop0_0_v_Seg0_dend_22_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_22_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_22_output0.record(&a_pop0[0].secondary_dend_14.v(0.10659498)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_22_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/59/v
        h(' objectvar v_pop0_0_v_Seg1_dend_22_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_22_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_22_output0.record(&a_pop0[0].secondary_dend_14.v(0.606595)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_22_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/60/v
        h(' objectvar v_pop0_0_v_Seg0_dend_23_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_23_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_23_output0.record(&a_pop0[0].secondary_dend_15.v(0.104553744)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_23_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/61/v
        h(' objectvar v_pop0_0_v_Seg1_dend_23_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_23_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_23_output0.record(&a_pop0[0].secondary_dend_15.v(0.60455376)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_23_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/62/v
        h(' objectvar v_pop0_0_v_Seg0_dend_24_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_24_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_24_output0.record(&a_pop0[0].tertiary_dend_0.v(0.1286071)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_24_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/63/v
        h(' objectvar v_pop0_0_v_Seg1_dend_24_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_24_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_24_output0.record(&a_pop0[0].tertiary_dend_0.v(0.6286071)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_24_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/64/v
        h(' objectvar v_pop0_0_v_Seg0_dend_25_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_25_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_25_output0.record(&a_pop0[0].tertiary_dend_1.v(0.12850428)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_25_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/65/v
        h(' objectvar v_pop0_0_v_Seg1_dend_25_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_25_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_25_output0.record(&a_pop0[0].tertiary_dend_1.v(0.6285043)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_25_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/66/v
        h(' objectvar v_pop0_0_v_Seg0_dend_26_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_26_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_26_output0.record(&a_pop0[0].tertiary_dend_2.v(0.128198)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_26_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/67/v
        h(' objectvar v_pop0_0_v_Seg1_dend_26_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_26_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_26_output0.record(&a_pop0[0].tertiary_dend_2.v(0.62819797)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_26_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/68/v
        h(' objectvar v_pop0_0_v_Seg1_dend_27_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_27_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_27_output0.record(&a_pop0[0].tertiary_dend_3.v(0.12769453)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_27_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/69/v
        h(' objectvar v_pop0_0_v_Seg0_dend_27_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_27_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_27_output0.record(&a_pop0[0].tertiary_dend_3.v(0.62769455)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_27_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/70/v
        h(' objectvar v_pop0_0_v_Seg1_dend_28_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_28_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_28_output0.record(&a_pop0[0].tertiary_dend_4.v(0.12700403)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_28_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/71/v
        h(' objectvar v_pop0_0_v_Seg0_dend_28_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_28_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_28_output0.record(&a_pop0[0].tertiary_dend_4.v(0.627004)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_28_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/72/v
        h(' objectvar v_pop0_0_v_Seg1_dend_29_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_29_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_29_output0.record(&a_pop0[0].tertiary_dend_5.v(0.12613992)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_29_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/73/v
        h(' objectvar v_pop0_0_v_Seg0_dend_29_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_29_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_29_output0.record(&a_pop0[0].tertiary_dend_5.v(0.62613994)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_29_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/74/v
        h(' objectvar v_pop0_0_v_Seg1_dend_30_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_30_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_30_output0.record(&a_pop0[0].tertiary_dend_6.v(0.12511827)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_30_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/75/v
        h(' objectvar v_pop0_0_v_Seg0_dend_30_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_30_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_30_output0.record(&a_pop0[0].tertiary_dend_6.v(0.62511826)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_30_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/76/v
        h(' objectvar v_pop0_0_v_Seg1_dend_31_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_31_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_31_output0.record(&a_pop0[0].tertiary_dend_7.v(0.12395706)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_31_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/77/v
        h(' objectvar v_pop0_0_v_Seg0_dend_31_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_31_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_31_output0.record(&a_pop0[0].tertiary_dend_7.v(0.62395704)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_31_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/78/v
        h(' objectvar v_pop0_0_v_Seg1_dend_32_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_32_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_32_output0.record(&a_pop0[0].quaternary_dend_0.v(0.12663768)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_32_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/79/v
        h(' objectvar v_pop0_0_v_Seg0_dend_32_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_32_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_32_output0.record(&a_pop0[0].quaternary_dend_0.v(0.6266377)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_32_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/80/v
        h(' objectvar v_pop0_0_v_Seg1_dend_33_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_33_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_33_output0.record(&a_pop0[0].quaternary_dend_1.v(0.12658542)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_33_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/81/v
        h(' objectvar v_pop0_0_v_Seg0_dend_33_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_33_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_33_output0.record(&a_pop0[0].quaternary_dend_1.v(0.6265854)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_33_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/82/v
        h(' objectvar v_pop0_0_v_Seg1_dend_34_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_34_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_34_output0.record(&a_pop0[0].quaternary_dend_2.v(0.12642922)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_34_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/83/v
        h(' objectvar v_pop0_0_v_Seg0_dend_34_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_34_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_34_output0.record(&a_pop0[0].quaternary_dend_2.v(0.6264292)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_34_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/84/v
        h(' objectvar v_pop0_0_v_Seg1_dend_35_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_35_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_35_output0.record(&a_pop0[0].quaternary_dend_3.v(0.12617072)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_35_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/85/v
        h(' objectvar v_pop0_0_v_Seg1_dend_35_output0_ ')
        h(' { v_pop0_0_v_Seg1_dend_35_output0_ = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_35_output0_.record(&a_pop0[0].quaternary_dend_3.v(0.62617075)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_35_output0_.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/86/v
        h(' objectvar v_pop0_0_v_Seg0_dend_36_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_36_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_36_output0.record(&a_pop0[0].quaternary_dend_4.v(0.12581268)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_36_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/87/v
        h(' objectvar v_pop0_0_v_Seg1_dend_36_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_36_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_36_output0.record(&a_pop0[0].quaternary_dend_4.v(0.62581265)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_36_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/88/v
        h(' objectvar v_pop0_0_v_Seg0_dend_37_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_37_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_37_output0.record(&a_pop0[0].quaternary_dend_5.v(0.12535878)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_37_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/89/v
        h(' objectvar v_pop0_0_v_Seg1_dend_37_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_37_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_37_output0.record(&a_pop0[0].quaternary_dend_5.v(0.62535876)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_37_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/90/v
        h(' objectvar v_pop0_0_v_Seg0_dend_38_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_38_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_38_output0.record(&a_pop0[0].quaternary_dend_6.v(0.124813624)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_38_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/91/v
        h(' objectvar v_pop0_0_v_Seg1_dend_38_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_38_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_38_output0.record(&a_pop0[0].quaternary_dend_6.v(0.6248136)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_38_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/92/v
        h(' objectvar v_pop0_0_v_Seg0_dend_39_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_39_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_39_output0.record(&a_pop0[0].quaternary_dend_7.v(0.124182574)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_39_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/93/v
        h(' objectvar v_pop0_0_v_Seg1_dend_39_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_39_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_39_output0.record(&a_pop0[0].quaternary_dend_7.v(0.6241826)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_39_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/94/v
        h(' objectvar v_pop0_0_v_Seg0_dend_40_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_40_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_40_output0.record(&a_pop0[0].quaternary_dend_8.v(0.12347163)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_40_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/95/v
        h(' objectvar v_pop0_0_v_Seg1_dend_40_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_40_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_40_output0.record(&a_pop0[0].quaternary_dend_8.v(0.6234716)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_40_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/96/v
        h(' objectvar v_pop0_0_v_Seg0_dend_41_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_41_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_41_output0.record(&a_pop0[0].quaternary_dend_9.v(0.12268727)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_41_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/97/v
        h(' objectvar v_pop0_0_v_Seg1_dend_41_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_41_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_41_output0.record(&a_pop0[0].quaternary_dend_9.v(0.6226873)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_41_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/97/v
        h(' objectvar v_pop0_0_v_Seg0_dend_42_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_42_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_42_output0.record(&a_pop0[0].quaternary_dend_9.v(0.6226873)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_42_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/99/v
        h(' objectvar v_pop0_0_v_Seg1_dend_42_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_42_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_42_output0.record(&a_pop0[0].quaternary_dend_10.v(0.62183636)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_42_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/100/v
        h(' objectvar v_pop0_0_v_Seg0_dend_43_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_43_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_43_output0.record(&a_pop0[0].quaternary_dend_11.v(0.12092593)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_43_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/101/v
        h(' objectvar v_pop0_0_v_Seg1_dend_43_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_43_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_43_output0.record(&a_pop0[0].quaternary_dend_11.v(0.62092596)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_43_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/102/v
        h(' objectvar v_pop0_0_v_Seg0_dend_44_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_44_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_44_output0.record(&a_pop0[0].quaternary_dend_12.v(0.11996318)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_44_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/103/v
        h(' objectvar v_pop0_0_v_Seg1_dend_44_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_44_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_44_output0.record(&a_pop0[0].quaternary_dend_12.v(0.61996317)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_44_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/104/v
        h(' objectvar v_pop0_0_v_Seg1_dend_45_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_45_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_45_output0.record(&a_pop0[0].quaternary_dend_13.v(0.1189552)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_45_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/105/v
        h(' objectvar v_pop0_0_v_Seg0_dend_45_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_45_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_45_output0.record(&a_pop0[0].quaternary_dend_13.v(0.6189552)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_45_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/106/v
        h(' objectvar v_pop0_0_v_Seg1_dend_46_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_46_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_46_output0.record(&a_pop0[0].quaternary_dend_14.v(0.11790902)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_46_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/107/v
        h(' objectvar v_pop0_0_v_Seg0_dend_46_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_46_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_46_output0.record(&a_pop0[0].quaternary_dend_14.v(0.617909)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_46_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/108/v
        h(' objectvar v_pop0_0_v_Seg1_dend_47_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_47_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_47_output0.record(&a_pop0[0].quaternary_dend_15.v(0.11683142)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_47_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/109/v
        h(' objectvar v_pop0_0_v_Seg0_dend_47_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_47_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_47_output0.record(&a_pop0[0].quaternary_dend_15.v(0.6168314)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_47_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/110/v
        h(' objectvar v_pop0_0_v_Seg1_dend_48_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_48_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_48_output0.record(&a_pop0[0].quinary_dend_0.v(0.12592824)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_48_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/111/v
        h(' objectvar v_pop0_0_v_Seg0_dend_48_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_48_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_48_output0.record(&a_pop0[0].quinary_dend_0.v(0.6259282)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_48_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/112/v
        h(' objectvar v_pop0_0_v_Seg1_dend_49_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_49_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_49_output0.record(&a_pop0[0].quinary_dend_1.v(0.12590945)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_49_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/113/v
        h(' objectvar v_pop0_0_v_Seg0_dend_49_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_49_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_49_output0.record(&a_pop0[0].quinary_dend_1.v(0.62590945)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_49_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/114/v
        h(' objectvar v_pop0_0_v_Seg1_dend_50_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_50_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_50_output0.record(&a_pop0[0].quinary_dend_2.v(0.12585315)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_50_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/115/v
        h(' objectvar v_pop0_0_v_Seg0_dend_50_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_50_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_50_output0.record(&a_pop0[0].quinary_dend_2.v(0.6258532)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_50_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/116/v
        h(' objectvar v_pop0_0_v_Seg1_dend_51_output0 ')
        h(' { v_pop0_0_v_Seg1_dend_51_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg1_dend_51_output0.record(&a_pop0[0].quinary_dend_3.v(0.12575957)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg1_dend_51_output0.resize((h.tstop * h.steps_per_ms) + 1)
        # Column: pop0/0/nRT/117/v
        h(' objectvar v_pop0_0_v_Seg0_dend_51_output0 ')
        h(' { v_pop0_0_v_Seg0_dend_51_output0 = new Vector() } ')
        h(' { v_pop0_0_v_Seg0_dend_51_output0.record(&a_pop0[0].quinary_dend_3.v(0.6257596)) } ')
        if self.abs_tol is None or self.rel_tol is None:

            h.v_pop0_0_v_Seg0_dend_51_output0.resize((h.tstop * h.steps_per_ms) + 1)

        self.initialized = False

        self.sim_end = -1 # will be overwritten

        setup_end = time.time()
        self.setup_time = setup_end - self.setup_start
        print("Setting up the network to simulate took %f seconds"%(self.setup_time))

    def run(self):

        self.initialized = True
        sim_start = time.time()
        if self.abs_tol is not None and self.rel_tol is not None:
            print("Running a simulation of %sms (cvode abs_tol = %sms, rel_tol = %sms; seed=%s)" % (h.tstop, self.abs_tol, self.rel_tol, self.seed))
        else:
            print("Running a simulation of %sms (dt = %sms; seed=%s)" % (h.tstop, h.dt, self.seed))

        try:
            h.run()
        except Exception as e:
            print("Exception running NEURON: %s" % (e))
            quit()


        self.sim_end = time.time()
        self.sim_time = self.sim_end - sim_start
        print("Finished NEURON simulation in %f seconds (%f mins)..."%(self.sim_time, self.sim_time/60.0))

        try:
            self.save_results()
        except Exception as e:
            print("Exception saving results of NEURON simulation: %s" % (e))
            quit()


    def advance(self):

        if not self.initialized:
            h.finitialize()
            self.initialized = True

        h.fadvance()


    ###############################################################################
    # Hash function to use in generation of random value
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _id32 (self,obj): 
        return int(hashlib.md5(obj.encode('utf-8')).hexdigest()[0:8],16)  # convert 8 first chars of md5 hash in base 16 to int


    ###############################################################################
    # Initialize the stim randomizer
    # This is copied from NetPyNE: https://github.com/Neurosim-lab/netpyne/blob/master/netpyne/simFuncs.py
    ###############################################################################
    def _init_stim_randomizer(self,rand, stimType, gid, seed): 
        #print("INIT STIM  %s; %s; %s; %s"%(rand, stimType, gid, seed))
        rand.Random123(self._id32(stimType), gid, seed)


    def save_results(self):

        print("Saving results at t=%s..."%h.t)

        if self.sim_end < 0: self.sim_end = time.time()


        # ######################   File to save: time.dat (time). Note, saving in SI units
        py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

        f_time_f2 = open('time.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...
        f_time_f2.close()
        print("Saved data to: time.dat")

        # ######################   File to save: nRTc_sim.dat (output0). Note, saving in SI units
        py_v_pop0_0_v_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_soma_0_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_soma_0_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_soma_0_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_soma_0_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_axon_0_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_axon_0_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_axon_0_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_axon_0_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_axon_1_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_axon_1_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_axon_1_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_axon_1_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_axon_2_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_axon_2_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_axon_2_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_axon_2_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_axon_3_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_axon_3_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_axon_3_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_axon_3_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_axon_4_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_axon_4_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_axon_4_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_axon_4_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_axon_5_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_axon_5_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_axon_5_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_axon_5_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_0_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_0_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_0_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_0_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_1_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_1_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_1_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_1_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_2_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_2_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_2_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_2_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_3_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_3_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_3_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_3_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_4_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_4_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_4_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_4_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_5_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_5_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_5_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_5_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_6_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_6_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_6_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_6_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_7_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_7_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_7_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_7_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_8_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_8_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_8_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_8_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_9_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_9_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_9_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_9_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_10_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_10_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_10_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_10_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_11_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_11_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_11_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_11_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_12_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_12_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_12_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_12_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_13_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_13_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_13_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_13_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_14_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_14_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_14_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_14_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_15_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_15_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_15_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_15_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_16_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_16_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_16_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_16_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_17_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_17_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_17_output0_ = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_17_output0_.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_18_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_18_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_18_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_18_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_19_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_19_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_19_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_19_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_20_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_20_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_20_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_20_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_21_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_21_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_21_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_21_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_22_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_22_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_22_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_22_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_23_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_23_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_23_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_23_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_24_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_24_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_24_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_24_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_25_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_25_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_25_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_25_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_26_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_26_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_26_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_26_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_27_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_27_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_27_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_27_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_28_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_28_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_28_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_28_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_29_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_29_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_29_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_29_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_30_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_30_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_30_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_30_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_31_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_31_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_31_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_31_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_32_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_32_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_32_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_32_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_33_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_33_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_33_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_33_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_34_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_34_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_34_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_34_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_35_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_35_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_35_output0_ = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_35_output0_.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_36_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_36_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_36_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_36_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_37_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_37_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_37_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_37_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_38_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_38_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_38_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_38_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_39_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_39_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_39_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_39_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_40_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_40_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_40_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_40_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_41_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_41_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_41_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_41_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_42_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_42_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_42_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_42_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_43_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_43_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_43_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_43_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_44_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_44_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_44_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_44_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_45_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_45_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_45_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_45_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_46_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_46_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_46_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_46_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_47_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_47_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_47_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_47_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_48_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_48_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_48_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_48_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_49_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_49_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_49_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_49_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_50_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_50_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_50_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_50_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg1_dend_51_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg1_dend_51_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage
        py_v_pop0_0_v_Seg0_dend_51_output0 = [ float(x  / 1000.0) for x in h.v_pop0_0_v_Seg0_dend_51_output0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

        f_output0_f2 = open('nRTc_sim.dat', 'w')
        num_points = len(py_v_time)  # Simulation may have been stopped before tstop...

        for i in range(num_points):
            f_output0_f2.write('%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t%e\t\n' % (py_v_time[i], py_v_pop0_0_v_output0[i], py_v_pop0_0_v_Seg0_soma_0_output0[i], py_v_pop0_0_v_Seg1_soma_0_output0[i], py_v_pop0_0_v_Seg0_axon_0_output0[i], py_v_pop0_0_v_Seg1_axon_0_output0[i], py_v_pop0_0_v_Seg0_axon_1_output0[i], py_v_pop0_0_v_Seg1_axon_1_output0[i], py_v_pop0_0_v_Seg0_axon_2_output0[i], py_v_pop0_0_v_Seg1_axon_2_output0[i], py_v_pop0_0_v_Seg0_axon_3_output0[i], py_v_pop0_0_v_Seg1_axon_3_output0[i], py_v_pop0_0_v_Seg0_axon_4_output0[i], py_v_pop0_0_v_Seg1_axon_4_output0[i], py_v_pop0_0_v_Seg0_axon_5_output0[i], py_v_pop0_0_v_Seg1_axon_5_output0[i], py_v_pop0_0_v_Seg0_dend_0_output0[i], py_v_pop0_0_v_Seg1_dend_0_output0[i], py_v_pop0_0_v_Seg0_dend_1_output0[i], py_v_pop0_0_v_Seg1_dend_1_output0[i], py_v_pop0_0_v_Seg0_dend_2_output0[i], py_v_pop0_0_v_Seg1_dend_2_output0[i], py_v_pop0_0_v_Seg0_dend_3_output0[i], py_v_pop0_0_v_Seg1_dend_3_output0[i], py_v_pop0_0_v_Seg0_dend_4_output0[i], py_v_pop0_0_v_Seg1_dend_4_output0[i], py_v_pop0_0_v_Seg0_dend_5_output0[i], py_v_pop0_0_v_Seg1_dend_5_output0[i], py_v_pop0_0_v_Seg0_dend_6_output0[i], py_v_pop0_0_v_Seg1_dend_6_output0[i], py_v_pop0_0_v_Seg0_dend_7_output0[i], py_v_pop0_0_v_Seg1_dend_7_output0[i], py_v_pop0_0_v_Seg0_dend_8_output0[i], py_v_pop0_0_v_Seg1_dend_8_output0[i], py_v_pop0_0_v_Seg1_dend_9_output0[i], py_v_pop0_0_v_Seg0_dend_9_output0[i], py_v_pop0_0_v_Seg1_dend_10_output0[i], py_v_pop0_0_v_Seg0_dend_10_output0[i], py_v_pop0_0_v_Seg1_dend_11_output0[i], py_v_pop0_0_v_Seg0_dend_11_output0[i], py_v_pop0_0_v_Seg1_dend_12_output0[i], py_v_pop0_0_v_Seg0_dend_12_output0[i], py_v_pop0_0_v_Seg1_dend_13_output0[i], py_v_pop0_0_v_Seg0_dend_13_output0[i], py_v_pop0_0_v_Seg1_dend_14_output0[i], py_v_pop0_0_v_Seg0_dend_14_output0[i], py_v_pop0_0_v_Seg1_dend_15_output0[i], py_v_pop0_0_v_Seg0_dend_15_output0[i], py_v_pop0_0_v_Seg1_dend_16_output0[i], py_v_pop0_0_v_Seg0_dend_16_output0[i], py_v_pop0_0_v_Seg1_dend_17_output0[i], py_v_pop0_0_v_Seg1_dend_17_output0_[i], py_v_pop0_0_v_Seg0_dend_18_output0[i], py_v_pop0_0_v_Seg1_dend_18_output0[i], py_v_pop0_0_v_Seg0_dend_19_output0[i], py_v_pop0_0_v_Seg1_dend_19_output0[i], py_v_pop0_0_v_Seg0_dend_20_output0[i], py_v_pop0_0_v_Seg1_dend_20_output0[i], py_v_pop0_0_v_Seg0_dend_21_output0[i], py_v_pop0_0_v_Seg1_dend_21_output0[i], py_v_pop0_0_v_Seg0_dend_22_output0[i], py_v_pop0_0_v_Seg1_dend_22_output0[i], py_v_pop0_0_v_Seg0_dend_23_output0[i], py_v_pop0_0_v_Seg1_dend_23_output0[i], py_v_pop0_0_v_Seg0_dend_24_output0[i], py_v_pop0_0_v_Seg1_dend_24_output0[i], py_v_pop0_0_v_Seg0_dend_25_output0[i], py_v_pop0_0_v_Seg1_dend_25_output0[i], py_v_pop0_0_v_Seg0_dend_26_output0[i], py_v_pop0_0_v_Seg1_dend_26_output0[i], py_v_pop0_0_v_Seg1_dend_27_output0[i], py_v_pop0_0_v_Seg0_dend_27_output0[i], py_v_pop0_0_v_Seg1_dend_28_output0[i], py_v_pop0_0_v_Seg0_dend_28_output0[i], py_v_pop0_0_v_Seg1_dend_29_output0[i], py_v_pop0_0_v_Seg0_dend_29_output0[i], py_v_pop0_0_v_Seg1_dend_30_output0[i], py_v_pop0_0_v_Seg0_dend_30_output0[i], py_v_pop0_0_v_Seg1_dend_31_output0[i], py_v_pop0_0_v_Seg0_dend_31_output0[i], py_v_pop0_0_v_Seg1_dend_32_output0[i], py_v_pop0_0_v_Seg0_dend_32_output0[i], py_v_pop0_0_v_Seg1_dend_33_output0[i], py_v_pop0_0_v_Seg0_dend_33_output0[i], py_v_pop0_0_v_Seg1_dend_34_output0[i], py_v_pop0_0_v_Seg0_dend_34_output0[i], py_v_pop0_0_v_Seg1_dend_35_output0[i], py_v_pop0_0_v_Seg1_dend_35_output0_[i], py_v_pop0_0_v_Seg0_dend_36_output0[i], py_v_pop0_0_v_Seg1_dend_36_output0[i], py_v_pop0_0_v_Seg0_dend_37_output0[i], py_v_pop0_0_v_Seg1_dend_37_output0[i], py_v_pop0_0_v_Seg0_dend_38_output0[i], py_v_pop0_0_v_Seg1_dend_38_output0[i], py_v_pop0_0_v_Seg0_dend_39_output0[i], py_v_pop0_0_v_Seg1_dend_39_output0[i], py_v_pop0_0_v_Seg0_dend_40_output0[i], py_v_pop0_0_v_Seg1_dend_40_output0[i], py_v_pop0_0_v_Seg0_dend_41_output0[i], py_v_pop0_0_v_Seg1_dend_41_output0[i], py_v_pop0_0_v_Seg0_dend_42_output0[i], py_v_pop0_0_v_Seg1_dend_42_output0[i], py_v_pop0_0_v_Seg0_dend_43_output0[i], py_v_pop0_0_v_Seg1_dend_43_output0[i], py_v_pop0_0_v_Seg0_dend_44_output0[i], py_v_pop0_0_v_Seg1_dend_44_output0[i], py_v_pop0_0_v_Seg1_dend_45_output0[i], py_v_pop0_0_v_Seg0_dend_45_output0[i], py_v_pop0_0_v_Seg1_dend_46_output0[i], py_v_pop0_0_v_Seg0_dend_46_output0[i], py_v_pop0_0_v_Seg1_dend_47_output0[i], py_v_pop0_0_v_Seg0_dend_47_output0[i], py_v_pop0_0_v_Seg1_dend_48_output0[i], py_v_pop0_0_v_Seg0_dend_48_output0[i], py_v_pop0_0_v_Seg1_dend_49_output0[i], py_v_pop0_0_v_Seg0_dend_49_output0[i], py_v_pop0_0_v_Seg1_dend_50_output0[i], py_v_pop0_0_v_Seg0_dend_50_output0[i], py_v_pop0_0_v_Seg1_dend_51_output0[i], py_v_pop0_0_v_Seg0_dend_51_output0[i], ))
        f_output0_f2.close()
        print("Saved data to: nRTc_sim.dat")

        save_end = time.time()
        save_time = save_end - self.sim_end
        print("Finished saving results in %f seconds"%(save_time))

        print("Done")

        quit()


if __name__ == '__main__':

    ns = NeuronSimulation(tstop=200.0, dt=0.01, seed=123, abs_tol=None, rel_tol=None)

    ns.run()

