TITLE Mod file for component: Component(id=sg_nRTil type=sineGenerator)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.11.0
         org.neuroml.model   v1.11.0
         jLEMS               v0.12.0

ENDCOMMENT

NEURON {
    POINT_PROCESS sg_nRTil
    ELECTRODE_CURRENT i
    RANGE weight                            : property
    RANGE phase                             : parameter
    RANGE delay                             : parameter
    RANGE duration                          : parameter
    RANGE amplitude                         : parameter
    RANGE period                            : parameter
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    
    weight = 1
    phase = 2                              : was: 2.0 (none)
    delay = 50 (ms)                        : was: 0.05 (time)
    duration = 200 (ms)                    : was: 0.2 (time)
    amplitude = 1.4 (nA)                   : was: 1.4E-9 (current)
    period = 50 (ms)                       : was: 0.05 (time)
}

STATE {
    i (nA) : dimension: current
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
}

BREAKPOINT {
    
    rates()
    if (t <  delay) {
        i = 0 ? standard OnCondition
    }
    
    if (t >=  delay  && t <   duration  +  delay) {
        i = weight  *  amplitude  * sin(  phase   + (2 * 3.14159265 * (t-  delay  )/  period  ) ) ? standard OnCondition
    }
    
    if (t >=   duration  +  delay) {
        i = 0 ? standard OnCondition
    }
    
    
}

PROCEDURE rates() {
    
    
     
    
}

